AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub "HelloWorldFunction"
      CodeUri: ../go_function.zip
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [x86_64]
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          ENV: !Sub "DEV"

Outputs:
  FunctionName:
    Description: "The name of the HelloWorld Lambda function"
    Value: !Ref HelloWorldFunction
    Export:
      Name: HelloWorldFunctionName

  FunctionArn:
    Description: "The ARN of the HelloWorld Lambda function"
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: HelloWorldFunctionArn
